---
- hosts: node1
  tasks:
    - name:
      set_fact:
        ip: 54.224.95.28
    
    - name: replace
      copy: src=ssh_config dest=/etc/ssh/ssh_config remote_src=no
    - name: restart sshd
      systemd:
        name: sshd
        state: restarted

    
    - name: create ssh
      command : ssh-keygen -q -t rsa -f /root/.ssh/id_rsa -C "" -N ""
      args:
        creates: /root/.ssh/id_rsa
    
    - name: copy to authorized keys
      shell: cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
       
#    - name: no verify
#      shell: 'ssh -o "StrictHostKeyChecking no" root@"{{ ip }}"'
#      shell: exit
#    - name: ssh to self
#      command: 'echo "yes \n" |  ssh root@"{{ ip }}"'
            
#      command: 'ssh root@"{{ ip }}"'
